/**
 * Which icon a name gets, cut out of material-icon-theme (MIT).
 *
 * GENERATED by scripts/build-file-icons.mjs. Do not edit by hand: add the
 * extension, filename or folder name to a list in that script and run it.
 *
 * These are names, not pictures. The pictures are static SVGs under
 * `public/file-icons/`, drawn with `<img>`, so the whole set costs the
 * bundle nothing beyond the few kilobytes of this table. `src/components/
 * file-icon.tsx` is what turns a name here into something on screen, and what
 * falls back to a lucide glyph for everything not listed.
 */

/** The theme this came from, so a bump can be told from a hand edit. */
export const ICON_THEME_VERSION = "5.38.1";

/** By file ending, lower-cased. Compound endings are matched longest-first. */
export const ICON_BY_EXTENSION: Record<string, string> = {
  "avif": "image",
  "bak": "database",
  "bash": "console",
  "bicep": "bicep",
  "bmp": "image",
  "c": "c",
  "cc": "cpp",
  "cfg": "settings",
  "cjs": "javascript",
  "clj": "clojure",
  "conf": "settings",
  "cpp": "cpp",
  "cs": "csharp",
  "css": "css",
  "csv": "table",
  "cts": "typescript",
  "d.ts": "typescript-def",
  "dart": "dart",
  "db": "database",
  "diff": "diff",
  "dll": "dll",
  "env": "tune",
  "eot": "font",
  "erl": "erlang",
  "ex": "elixir",
  "exe": "exe",
  "exs": "elixir",
  "fish": "console",
  "gif": "image",
  "go": "go",
  "graphql": "graphql",
  "gz": "zip",
  "h": "h",
  "hpp": "hpp",
  "hs": "haskell",
  "htm": "html",
  "html": "html",
  "ico": "image",
  "ini": "settings",
  "ipynb": "jupyter",
  "java": "java",
  "jpeg": "image",
  "jpg": "image",
  "js": "javascript",
  "json": "json",
  "json5": "json",
  "jsonc": "json",
  "jsx": "react",
  "kt": "kotlin",
  "less": "less",
  "lock": "lock",
  "log": "log",
  "lua": "lua",
  "md": "markdown",
  "mdx": "mdx",
  "mjs": "javascript",
  "mov": "video",
  "mp3": "audio",
  "mp4": "video",
  "mts": "typescript",
  "nim": "nim",
  "nix": "nix",
  "ogg": "video",
  "otf": "font",
  "patch": "git",
  "pdf": "pdf",
  "php": "php",
  "pl": "prolog",
  "png": "image",
  "proto": "proto",
  "ps1": "powershell",
  "py": "python",
  "pyi": "python",
  "r": "r",
  "rb": "ruby",
  "rs": "rust",
  "rst": "markdown",
  "sass": "sass",
  "scala": "scala",
  "scss": "sass",
  "sh": "console",
  "so": "dll",
  "spec.js": "test-js",
  "spec.ts": "test-ts",
  "spec.tsx": "test-jsx",
  "sql": "database",
  "sqlite": "database",
  "svg": "svg",
  "swift": "swift",
  "tar": "zip",
  "test.js": "test-js",
  "test.ts": "test-ts",
  "test.tsx": "test-jsx",
  "tex": "tex",
  "toml": "toml",
  "ts": "typescript",
  "tsv": "table",
  "tsx": "react_ts",
  "ttf": "font",
  "txt": "document",
  "vim": "vim",
  "wasm": "webassembly",
  "wav": "audio",
  "webm": "video",
  "webp": "image",
  "woff": "font",
  "woff2": "font",
  "xml": "xml",
  "yaml": "yaml",
  "yml": "yaml",
  "zig": "zig",
  "zip": "zip",
  "zsh": "console"
};

/** By whole filename, lower-cased. Beats the ending. */
export const ICON_BY_NAME: Record<string, string> = {
  ".editorconfig": "editorconfig",
  ".env.local": "tune",
  ".eslintrc.json": "eslint",
  ".gitattributes": "git",
  ".gitignore": "git",
  ".gitkeep": "git",
  ".gitmodules": "git",
  ".npmrc": "npm",
  ".nvmrc": "nodejs",
  ".prettierrc": "prettier",
  "agents.md": "agent",
  "changelog.md": "changelog",
  "cmakelists.txt": "cmake",
  "compose.yaml": "docker",
  "contributing.md": "contributing",
  "docker-compose.yaml": "docker",
  "docker-compose.yml": "docker",
  "dockerfile": "docker",
  "eslint.config.js": "eslint",
  "gemfile": "gemfile",
  "go.mod": "go-mod",
  "go.sum": "go-mod",
  "jsconfig.json": "jsconfig",
  "justfile": "just",
  "licence": "license",
  "license": "license",
  "makefile": "makefile",
  "next.config.js": "next",
  "package-lock.json": "nodejs",
  "package.json": "nodejs",
  "playwright.config.ts": "playwright",
  "pnpm-lock.yaml": "pnpm",
  "postcss.config.js": "postcss",
  "procfile": "heroku",
  "pyproject.toml": "python-misc",
  "rakefile": "ruby",
  "readme.md": "readme",
  "requirements.txt": "python-misc",
  "tailwind.config.js": "tailwindcss",
  "tsconfig.json": "tsconfig",
  "vite.config.ts": "vite",
  "vitest.config.ts": "vitest",
  "yarn.lock": "yarn"
};

/** By folder name, lower-cased: shut first, then open. */
export const ICON_BY_FOLDER: Record<string, readonly [string, string]> = {
  ".git": [
    "folder-git",
    "folder-git-open"
  ],
  ".github": [
    "folder-github",
    "folder-github-open"
  ],
  ".vscode": [
    "folder-vscode",
    "folder-vscode-open"
  ],
  "__tests__": [
    "folder-test",
    "folder-test-open"
  ],
  "android": [
    "folder-android",
    "folder-android-open"
  ],
  "api": [
    "folder-api",
    "folder-api-open"
  ],
  "app": [
    "folder-app",
    "folder-app-open"
  ],
  "archive": [
    "folder-archive",
    "folder-archive-open"
  ],
  "assets": [
    "folder-resource",
    "folder-resource-open"
  ],
  "audio": [
    "folder-audio",
    "folder-audio-open"
  ],
  "bin": [
    "folder-dist",
    "folder-dist-open"
  ],
  "build": [
    "folder-dist",
    "folder-dist-open"
  ],
  "client": [
    "folder-client",
    "folder-client-open"
  ],
  "components": [
    "folder-components",
    "folder-components-open"
  ],
  "config": [
    "folder-config",
    "folder-config-open"
  ],
  "controllers": [
    "folder-controller",
    "folder-controller-open"
  ],
  "coverage": [
    "folder-coverage",
    "folder-coverage-open"
  ],
  "css": [
    "folder-css",
    "folder-css-open"
  ],
  "database": [
    "folder-database",
    "folder-database-open"
  ],
  "dist": [
    "folder-dist",
    "folder-dist-open"
  ],
  "docs": [
    "folder-docs",
    "folder-docs-open"
  ],
  "examples": [
    "folder-examples",
    "folder-examples-open"
  ],
  "fonts": [
    "folder-font",
    "folder-font-open"
  ],
  "hooks": [
    "folder-hook",
    "folder-hook-open"
  ],
  "i18n": [
    "folder-i18n",
    "folder-i18n-open"
  ],
  "images": [
    "folder-images",
    "folder-images-open"
  ],
  "ios": [
    "folder-ios",
    "folder-ios-open"
  ],
  "lib": [
    "folder-lib",
    "folder-lib-open"
  ],
  "log": [
    "folder-log",
    "folder-log-open"
  ],
  "middleware": [
    "folder-middleware",
    "folder-middleware-open"
  ],
  "migrations": [
    "folder-migrations",
    "folder-migrations-open"
  ],
  "models": [
    "folder-class",
    "folder-class-open"
  ],
  "node_modules": [
    "folder-node",
    "folder-node-open"
  ],
  "out": [
    "folder-dist",
    "folder-dist-open"
  ],
  "packages": [
    "folder-packages",
    "folder-packages-open"
  ],
  "pages": [
    "folder-views",
    "folder-views-open"
  ],
  "plugins": [
    "folder-plugin",
    "folder-plugin-open"
  ],
  "public": [
    "folder-public",
    "folder-public-open"
  ],
  "routes": [
    "folder-routes",
    "folder-routes-open"
  ],
  "scripts": [
    "folder-scripts",
    "folder-scripts-open"
  ],
  "server": [
    "folder-server",
    "folder-server-open"
  ],
  "src": [
    "folder-src",
    "folder-src-open"
  ],
  "styles": [
    "folder-css",
    "folder-css-open"
  ],
  "target": [
    "folder-target",
    "folder-target-open"
  ],
  "temp": [
    "folder-temp",
    "folder-temp-open"
  ],
  "templates": [
    "folder-template",
    "folder-template-open"
  ],
  "test": [
    "folder-test",
    "folder-test-open"
  ],
  "tests": [
    "folder-test",
    "folder-test-open"
  ],
  "themes": [
    "folder-theme",
    "folder-theme-open"
  ],
  "tools": [
    "folder-tools",
    "folder-tools-open"
  ],
  "utils": [
    "folder-utils",
    "folder-utils-open"
  ],
  "video": [
    "folder-video",
    "folder-video-open"
  ],
  "views": [
    "folder-views",
    "folder-views-open"
  ]
};

/** What anything unrecognised gets, when a material icon is wanted anyway. */
export const ICON_FALLBACK = {
  "file": "file",
  "folder": "folder",
  "folderOpen": "folder-open"
} as const;

/** Where a name here is served from. */
export function iconUrl(icon: string): string {
  return `/file-icons/${icon}.svg`;
}
